import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  buildSidebar: [
    { type: 'link', label: '← Developer Docs', href: '/developers' },
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
