import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * The user docs sidebar.
 *
 * Diataxis is the skeleton: start / tutorials / guides / reference are the
 * directory structure. Tiers are a table of contents only. They group pages
 * inside /tutorials/ and never appear in a URL, so a page can be re-tiered
 * without breaking a link.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get started',
      link: { type: 'doc', id: 'start/index' },
      items: [
        'start/install',
        'start/first-recording',
        'start/see-your-results',
        'start/where-next',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: { type: 'doc', id: 'tutorials/index' },
      items: [
        {
          type: 'category',
          label: 'Tier 1: Beginner',
          collapsed: false,
          items: [
            'tutorials/hardware',
            'tutorials/single-camera',
            'tutorials/calibrate',
            'tutorials/multi-camera',
            'tutorials/find-your-data',
            'tutorials/blender',
          ],
        },
        {
          type: 'category',
          label: 'Tier 2: Intermediate',
          items: [
            'tutorials/better-calibration',
            'tutorials/ground-plane',
            'tutorials/choose-a-tracker',
            'tutorials/post-processing',
            'tutorials/capture-environment',
          ],
        },
        {
          type: 'category',
          label: 'Tier 3: Advanced',
          items: [
            'tutorials/analyze-in-python',
            'tutorials/custom-pipeline',
            'tutorials/batch-processing',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to guides',
      link: { type: 'doc', id: 'guides/index' },
      // Hand-listed, not autogenerated: Docusaurus has no built-in way to
      // autogenerate a folder's items while excluding that folder's own
      // index page, so autogeneration here duplicated "How-to guides" as
      // both the category link and its own first child. Add new guides to
      // both this list and the Discord-derived source when that lands.
      items: [
        'guides/installation-troubleshooting',
        'guides/calibration-troubleshooting',
        'guides/gpu-setup',
        'guides/camera-setup',
        'guides/posthoc-mocap',
        'guides/blender-export',
        'guides/export-formats',
        'guides/yolo-cropping',
        'guides/report-a-bug',
        'guides/request-a-feature',
        'guides/cite-freemocap',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'reference/index' },
      items: [
        'reference/recording-structure',
        'reference/data-arrays',
        'reference/coordinate-conventions',
        'reference/skeleton-models',
        'reference/configuration',
        'reference/rest-api',
        'reference/websocket-api',
        'reference/cli',
        'reference/system-requirements',
      ],
    },
    {
      type: 'category',
      label: 'About',
      link: { type: 'doc', id: 'about/index' },
      items: [
        'about/about-us',
        'about/faq',
        'about/code-of-conduct',
        'about/privacy',
        'about/roadmap',
        'about/how-these-docs-are-written',
      ],
    },
  ],
};

export default sidebars;
