import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/** Shared by every sub-repo docs instance. One shape, so a reader who has
 *  navigated one repo's docs knows how to navigate all of them. */
const sidebars: SidebarsConfig = {
  externalSidebar: [
    { type: 'link', label: '← Developer Docs', href: '/developers' },
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
